# Generated by Django 5.2.8 on 2025-11-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_ownerregistration_options_and_more"),
        ("accounts", "0003_alter_workerregistration_email"),
    ]

    operations = []
