# Generated by Django 5.2.7 on 2025-11-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20251115_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerregistration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='workerregistration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
